### ISSUE TITLE
Whats the benefit over the existing solutions?

### ISSUE THREAD

**Issue by gajus** [FezVrasta/react-element-queries#1]
As I am researching the available solutions, what benefit does this offer over all the equivalent solutions?

* https://github.com/d6u/react-container-query
* https://github.com/joeybaker/react-element-query
* ... (quite a few come up in Google search)

**Comment by FezVrasta** [comment]
I just looked at them quickly, but seems like they use a different resize detection approach.

**Comment by gajus** [comment]
I doubt this is more performant/ x-browser available than https://github.com/d6u/react-container-query#performance.

But then I have no benchmarks to back it up.

**Comment by gajus** [comment]
Something like this would be immensely valuable, best contributed to an existing/ mature project. https://github.com/d6u/react-container-query/issues/57

I am just going to leave you with https://hackernoon.com/the-wheels-of-open-source-weve-got-many-of-them-b345b74b1496

**Comment by FezVrasta** [comment]
The project you linked weights 12KB gzipped, requires react-dom, lodash, container-query-tookit and resize-observer-lite.
The code base is really huge.

Mine requires only itself 800B gzipped + react-resize-aware (1.2kb).

I just needed a simple and performant component and I wanted to experiment with some new API.

I don't have time to refactor a code-base of someone else and I don't neither want to spend time waiting for approval from the maintainers. That's why I created this library.

About the x-browser compatibility, I'm not 100% sure but I think my method is supported on all the existing browsers.

I really like open source, I tried in the past to contribute to one of the existing projects (probably ResizeMe?) and I clashed with other's ideas and preferences.
Create my own open source project was the easiest way to get what I needed and contribute back to the community.

I hope my points make sense.

**Comment by d6u** [comment]
Yeah, somebody has to come out and improve the size :P. A analysis of where is size come from would be really helpful. 

I suspect the majority of the weight come from https://github.com/wnr/element-resize-detector, instead of react-dom, etc. since if you import react, very likely you also import react-dom. I'm just too exhaust in my day job, so I don't have time to perfect this.
